version: '3.7'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=qwerty
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=qwerty
  web:
    build: .
    command: python /usr/src/djangoproj/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/djangoproj
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  postgres_data:
