# Generated by Django 4.0.3 on 2022-03-25 12:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SteelStructureFabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TransportDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('unloading_date', models.DateField()),
                ('doc_id', models.CharField(max_length=64, null=True)),
                ('weight', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('UN', 'Unloaded'), ('RE', 'Refunded')], max_length=2, null=True)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoproj.steelstructurefabric')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('value', models.FloatField(null=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoproj.transportdelivery')),
            ],
        ),
    ]
