# Generated by Django 4.0.3 on 2022-03-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoproj', '0003_excelfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfile',
            name='file',
            field=models.FileField(upload_to='', verbose_name='excel/'),
        ),
    ]
